### ISSUE TITLE
requiring bug.

### ISSUE THREAD

**Issue by faridu86** [smali-kazmi/detect-mobile-browser#16]
Hi @smali-kazmi ,

I tried to require it as `var mobileBrowser = require( 'detect-browser');`, it was giving me error as `Cannot find module 'detect-browser'`, but when I tried `var mobileBrowser = require( path.join(global.config.root, '/node_modules/detect-mobile-browser/detect-browser'));`, it worked fine.

**Comment by smali-kazmi** [comment]
please change `var mobileBrowser = require( 'detect-browser');` to `var mobileBrowser = require( 'detect-mobile-browser');`
